package com.incredigrimm.projecteuler;

/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*/


public class Problem2 {
	public static void main(String[] args) {
		int fibsum = 0;
		int a = 0;
		int b = 1;
		int finalsum = 0;
		while (fibsum <= 4000000){
			fibsum = a+b;
			a=b;
			b=fibsum;
			if(fibsum%2==0)
				finalsum+=fibsum;
		}
		System.out.println("The sum of the even-valued terms is: " + finalsum);
	}
}
